--@summary:克制关系 坦克>飞机>步兵
Setting={
	Runtime={
		ActiveMode={
			Interval=600,--每1分钟执行一次主动检查
			--@summary:上次主动操作开始的时间
			LastActiveTime=0,
		},
		
	},
	Expedition={
		--@summary:是否自动补充体力
		PlayerEnergySupply=false,
		PlayerMaxEnergy=100,
		--@summary:targetInfo[1]={Enemy=1,Rank={max=11,min=10}}
		--@property Enemy:由左至右依次顺序1-7
		--@property Rank:{max=1,min=1}目标的等级范围
		--@property Action:0-Dialog_OK 1-5:对应地图中按钮
		--@property Troop:0-默认 5-最高等级 6-最大负重 7-最快行军 8-均衡搭配 1到4-编队
		TargetInfo={
			[1]={Enemy=0,Rank={max=12,min=11},Action=0,Troop=0},
			[2]={Enemy=0,Rank={max=10,min=9},Action=0,Troop=0},
			[3]={Enemy=2,Rank={max=12,min=11},Action=5,Troop=0}
		}
	},
	Conscription={
		conscript={
			[1]={Enable=false,Description="坦克"},
			[2]={Enable=false,Description="空军"},
			[3]={Enable=false,Description="步兵"},
			[4]={Enable=false,Description="战车"},
			[5]={Enable=false,Description="城防"},
		}
	},
	Party={
		Gift={
			Enable=true,
			EnableOnekeyAttain=true,
		},
		Task={
			Enable=true,
		},
		Treasure={
			Enable=true,
			AssistOther={
				Enable=true,
				--1:绿色 2:蓝色 3:紫色 4:金色
				minTreasure=2,
			},
			Self={
				Enable=true,
				minTreasure=2,
			}
		}
	}
}

Const={
	Toolbar={
		scene={
			[1]="城市",
			[2]="世界",
			[3]="子菜单",
			[4]="其他"
		}
	},
	Expedition={
		PlayerEnergy={
			[1]=5,--野怪
			[2]=15,--兵营
			[3]=0,
			[4]=0,
			[5]=0,
			[6]=0,
			[7]=0,
		},
		EnemyDescription={
			[1]="野怪",
			[2]="兵营",
			[3]="矿石",
			[4]="石油",
			[5]="合金",
			[6]="稀土",
			[7]="基地",
		},
		TargetButton={
			[1]={200,590},
			[2]={250,485},
			[3]={350,425},
			[4]={470,485},
			[5]={530,590}
		}
	}
}