require "Setting.SettingUserInterface"
require "SettingBase.Init"

require "Form"
require "Application"
require "Building.normal"
require "Building.pandect"
require "Building.Building"
require "Building.skill"
require "ToolBar"
require "OCR"
require "Setting.Hud"